name: Deploy static HTML to domain
defaults:
  run:
    shell: bash

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "static-deploy"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Clone repository
        run: git clone https://github.com/odysen/infra_websitePlaceholder
      - name: Remove previous artifact
        run: rm -rf infra_websiteProduction
      - name: Move in-place
        run: mv infra_websitePlaceholder infra_websiteProduction